modLoader="javafml"
loaderVersion="[40,)"
license="None"
logoFile="banner.png"

[[mods]]
modId="respawningpets"
version="1.1.3"
displayName="Eternal Pets"
credits="§8Created by §5☆Lunar Eclipse Studios☆"
displayURL="https://lunareclipse.studio/eternal-pets"
issueTrackerURL="https://github.com/LunarEclipseStudios/eternal-pets/issues"
authors="Bret06"
description='''We all love pets in Minecraft, but we hate when they die. Eternal pets is a mod/datapack that adds a pet respawning mechanic to the parrot, the cat, and the wolf!'''

[[dependencies.respawningpets]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19, 1.20]"
    ordering="NONE"
    side="BOTH"

[[dependencies.respawningpets]]
    modId="respawningpets"
    mandatory=true
    versionRange="[1.1.3]"
    ordering="NONE"
    side="BOTH"



