modLoader = "lowcodefml"
loaderVersion="[40,)"
license="CC BY-NC-SA 4.0"
issueTrackerURL="https://discord.lunareclipse.studio"
showAsResourcePack = false

[[mods]]
modId="respawningpets"
version="1.3.2"
displayName="Eternal Pets"
credits="§8Created by §5☆Lunar Eclipse Studios☆"
displayURL="https://lunareclipse.studio/creations/eternal-pets"
logoFile="banner.png"
authors="Bret06"
description='''We all love pets in Minecraft, but we hate when they die. Eternal pets is a mod/datapack that adds a pet respawning mechanic to the parrot, the cat, and the wolf!'''

[[dependencies.respawningpets]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21,1.21.4]"
    ordering="NONE"
    side="BOTH"